apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: xeodocs-dev
servers: 1
agents: 3
registries:
  create:
    name: registry
    hostPort: "12030"
ports:
- port: 12020:12020
  nodeFilters:
  - loadbalancer
options:
  k3d:
    wait: true
