apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.dev.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  ports:
    - name: "12020"
      port: 12020
      targetPort: 12020
  selector:
    io.kompose.service: gateway
