apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: influxdb-data
  name: influxdb-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
