FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o service ./cmd/auth

FROM alpine:latest

COPY --from=builder /app/service /service
# This is required because the auth service uses goose for database migrations.
COPY --from=builder /app/internal/shared/db/migrations /app/internal/shared/db/migrations

CMD ["/service"]