FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o service ./cmd/auth

FROM alpine:latest

COPY --from=builder /app/service /service
COPY --from=builder /app/internal/shared/db /app/internal/shared/db

CMD ["/service"]