FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o service ./cmd/auth

FROM gcr.io/distroless/static

COPY --from=builder /app/service /service

CMD ["/service"]